services:
  - type: web
    name: jobyaari-blog-portal
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install && npm run build
      php artisan storage:link
    startCommand: heroku-php-apache2 public/
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: database/database.sqlite